substitutions:
  _UI_BUCKET: ""
  _DEPLOY_SA_RESOURCE: ""
  _VITE_SDZ_API_URL: ""
  _VITE_FIREBASE_API_KEY: ""
  _VITE_FIREBASE_AUTH_DOMAIN: ""
  _VITE_FIREBASE_PROJECT_ID: ""

serviceAccount: ${_DEPLOY_SA_RESOURCE}

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node:20
    id: build-ui
    dir: web/ui
    entrypoint: bash
    env:
      - VITE_SDZ_API_URL=${_VITE_SDZ_API_URL}
      - VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
    args:
      - -c
      - npm ci && npm run build

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: sync-ui
    entrypoint: bash
    args:
      - -c
      - |
        gsutil -m rsync -r -d web/ui/dist gs://${_UI_BUCKET}
        gsutil -h "Cache-Control:no-cache, max-age=0" cp web/ui/dist/index.html gs://${_UI_BUCKET}/index.html
